# Generated by Django 6.0 on 2026-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guestuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('SUPER_ADMIN', 'Super Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
