# Generated by Django 6.0 on 2026-02-17 07:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guestuser'),
        ('payment', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='GuestUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guestuser'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cart_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(max_length=255), blank=True, default=list),
        ),
    ]
