# Generated by Django 6.0 on 2026-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_guestuser_payment_cart_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='GuestUser',
            new_name='guest_user',
        ),
    ]
