# Generated by Django 6.0 on 2026-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_shipping_address_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
