# Generated by Django 6.0 on 2026-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_guest_name_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='guest_name',
            new_name='guest_user',
        ),
    ]
